# permissions for end users to edit horizontalautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-horizontalautoscaler-editor-role
rules:
- apiGroups:
  - karpenter.sh
  resources:
  - horizontalautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - karpenter.sh
  resources:
  - horizontalautoscalers/status
  verbs:
  - get
