{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.karpenter.sh
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: validation.webhook.karpenter.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "karpenter.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    sideEffects: None
    rules:
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1alpha5
        operations:
          - CREATE
          - UPDATE
        resources:
          - provisioners
          - provisioners/status
        scope: '*'
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - nodeclaims
          - nodeclaims/status
        scope: '*'
      - apiGroups:
          - karpenter.sh
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - nodepools
          - nodepools/status
        scope: '*'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.config.karpenter.sh
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: validation.webhook.config.karpenter.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "karpenter.fullname" . }}
        namespace: {{ .Release.Namespace }}
        port: {{ .Values.webhook.port }}
    failurePolicy: Fail
    sideEffects: None
    objectSelector:
      matchLabels:
        app.kubernetes.io/part-of: {{ template "karpenter.name" . }}
{{- end }}