[build]
base = "website/"
publish = "public"
command = "npm install; hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.120.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


[context.split1]
command = "npm install; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.120.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm install; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.120.3"

[context.branch-deploy]
command = "npm install; hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.120.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
