name: AlphaE2EScaleTrigger
on:
  schedule:
    - cron: '7 18 * * *'
  workflow_run:
    workflows: [ApprovalComment]
    types: [completed]
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: 'us-west-2'
        type: choice
        options:
          - "us-east-1"
          - "us-west-2"
      cleanup:
        required: true
        default: true
        type: boolean
      enable_metrics:
        required: true
        default: false
        type: boolean
jobs:
  resolve:
    if: (github.repository == 'aws/karpenter' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')) || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/resolve-args.yaml
    with:
      allowed_comment: "alpha-scale"
  alpha-scale:
    needs: [resolve]
    if: needs.resolve.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Alpha/Scale
      git_ref: ${{ needs.resolve.outputs.GIT_REF }}
      region: ${{ inputs.region || 'us-west-2' }}
      enable_metrics: ${{ inputs.enable_metrics || true }}
      workflow_trigger: "alpha-scale"
      cleanup: ${{ inputs.cleanup || true }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
