name: ApprovalComment
on:
  pull_request_review:
    types: [submitted]

jobs:
  approval-comment:
    if: startsWith(github.event.review.body, '/karpenter snapshot') || startsWith(github.event.review.body, '/karpenter scale')
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Save info about the review comment as an artifact for other workflows that run on workflow_run to download them
        run: |
          mkdir -p /tmp/artifacts
          echo ${{ github.event.review.body }} >> /tmp/artifacts/metadata.txt
          echo ${{ github.event.pull_request.number }} >> /tmp/artifacts/metadata.txt
          echo ${{ github.event.review.commit_id }} >> /tmp/artifacts/metadata.txt
          cat /tmp/artifacts/metadata.txt
      - uses: ./.github/actions/upload-artifact
