name: "CodeGenCI"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * MON'
jobs:
  codegen:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      pull-requests: write # name: Create Pull Request
      contents: write # name: Create Pull Request
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/install-deps
        with:
          use-cache: false
      - run: |
          git config user.name "APICodeGen"
          git config user.email "APICodeGen@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config pull.rebase false
      - uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.READONLY_ACCOUNT_ID }}:role/${{ vars.READONLY_ROLE_NAME }}'
          aws-region: ${{ vars.READONLY_REGION }}
      - run: make codegen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GIT_PUSH: true
      - id: detect-changes
        run: |
          # If we have a committed change, mark that we committed with a variable
          if [[ $(git rev-list --count main..codegen) != "0" ]]; then
            echo APICodeGenUpdate=true >> "$GITHUB_OUTPUT"
          fi
      - name: Create Pull Request
        if: steps.detect-changes.outputs.APICodeGenUpdate == 'true'
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'chore: Update data from AWS APIs',
              owner,
              repo,
              head: 'codegen',
              base: 'main',
              body: [
                'Updates auto generated files with data from the AWS APIs for pricing and VPC limits. Please remove the branch after merging.',
                'This PR is generated by [APICodeGen](https://github.com/aws/karpenter/actions/workflows/codegen.yml).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['aws', 'dependencies']
            });
      - name: notify slack of success or failure
        uses: ./.github/actions/e2e/slack/notify
        if: (success() || failure())
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          suite: codegen