name: DryRunGen
on:
  push:
    branches:
      - 'main'
      - 'release-v*'
      - 'staging/*'
jobs:
  dryrun-gen:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
    if: github.repository == 'aws/karpenter-provider-aws'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/install-deps
      - uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: 'arn:aws:iam::${{ vars.READONLY_ACCOUNT_ID }}:role/${{ vars.READONLY_ROLE_NAME }}'
          aws-region: ${{ vars.READONLY_REGION }}
      - run: make docgen
      - run: make codegen
        env:
          ENABLE_GIT_PUSH: false
      - run: make prepare-website
        env:
          GIT_TAG: v0.10000.0 # Mock version for testing website generation
