name: E2EUpgrade
on:
  workflow_dispatch:
    inputs:
      from_git_ref:
        type: string
        required: true
      region:
        type: choice
        options:
          - "us-east-2"
          - "us-west-2"
        default: "us-east-2"
      to_git_ref:
        type: string
      k8s_version:
        type: choice
        options:
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
          - "1.27"
        default: "1.27"
  workflow_call:
    inputs:
      from_git_ref:
        type: string
        required: true
      to_git_ref:
        type: string
      region:
        type: string 
        default: "us-east-2"
      event_name:
        type: string
        required: true
      k8s_version:
        type: string
        default: "1.27"
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  statuses: write
jobs:
  run-suite:
    name: suite-upgrade
    runs-on: ubuntu-latest
    steps:
      # This additional checkout can be removed when the commit status action is added to the from_git_ref version of Karpenter
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.to_git_ref }}
      - if: always() && inputs.event_name == 'workflow_run'
        uses: ./.github/actions/commit-status/start
        with:
          name: "${{ github.workflow }} / e2e (Upgrade) / ${{ github.job }} (snapshot)"
          git_ref: ${{ inputs.to_git_ref }}
      - uses: ./.github/actions/install-deps
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.from_git_ref }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: ${{ inputs.region }}
          role-duration-seconds: 21600
      - name: generate cluster name
        run: |
          CLUSTER_NAME="upgrade-$RANDOM$RANDOM"
          echo "Using cluster name \"$CLUSTER_NAME\""
          echo CLUSTER_NAME=$CLUSTER_NAME >> $GITHUB_ENV
      - name: create eks cluster '${{ env.CLUSTER_NAME }}'
        uses: ./.github/actions/e2e/create-cluster
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          k8s_version: ${{ inputs.k8s_version }}
          ip_family: IPv4 # Set the value to IPv6 if IPv6 suite, else IPv4
          git_ref: ${{ inputs.from_git_ref }}
      - name: install prometheus
        uses: ./.github/actions/e2e/install-prometheus
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ vars.PROMETHEUS_REGION }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          workspace_id: ${{ vars.WORKSPACE_ID }}
          git_ref: ${{ inputs.from_git_ref }}
      - name: install karpenter
        uses: ./.github/actions/e2e/install-karpenter
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          git_ref: ${{ inputs.from_git_ref }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.to_git_ref }}
      - name: upgrade eks cluster '${{ env.CLUSTER_NAME }}'
        uses: ./.github/actions/e2e/create-cluster
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          k8s_version: ${{ inputs.k8s_version }}
          ip_family: IPv4 # Set the value to IPv6 if IPv6 suite, else IPv4
          git_ref: ${{ inputs.to_git_ref }}
      - name: upgrade prometheus
        uses: ./.github/actions/e2e/install-prometheus
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ vars.PROMETHEUS_REGION }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          workspace_id: ${{ vars.WORKSPACE_ID }}
          git_ref: ${{ inputs.to_git_ref }}
      - name: upgrade crds
        uses: ./.github/actions/e2e/upgrade-crds
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          git_ref: ${{ inputs.to_git_ref }}
      - name: upgrade karpenter
        uses: ./.github/actions/e2e/install-karpenter
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          git_ref: ${{ inputs.to_git_ref }}
      - name: run the Upgrade test suite
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}
          TEST_SUITE="Integration" make e2etests
      - name: notify slack of success or failure
        uses: ./.github/actions/e2e/slack/notify
        if: (success() || failure()) && inputs.event_name != 'workflow_run' && inputs.event_name != 'conformance'
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          suite: Upgrade
          k8s_version: ${{ inputs.k8s_version }}
          event_name: ${{ inputs.event_name }}
          git_ref: ${{ inputs.to_git_ref }}
      - name: dump logs on failure
        uses: ./.github/actions/e2e/dump-logs
        if: failure() || cancelled()
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
      - name: cleanup karpenter and cluster '${{ env.CLUSTER_NAME }}' resources
        uses: ./.github/actions/e2e/cleanup
        if: always()
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ env.CLUSTER_NAME }}
          git_ref: ${{ inputs.to_git_ref }}
      - if: always() && inputs.event_name == 'workflow_run'
        uses: ./.github/actions/commit-status/end
        with:
          name: "${{ github.workflow }} / e2e (Upgrade) / ${{ github.job }} (snapshot)"
          git_ref: ${{ inputs.to_git_ref }}
