name: E2EMatrixTrigger
on:
  schedule:
    - cron: '7 */8 * * *'
  push:
    branches:
      - 'main'
      - 'release-v*'
  workflow_run:
    workflows:
      - ApprovalComment
    types:
      - completed
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: 'us-east-2'
        type: choice
        options:
          - "us-east-1"
          - "us-east-2"
      cleanup:
        required: true
        default: true
        type: boolean
jobs:
  resolve:
    if: (github.repository == 'aws/karpenter-provider-aws' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')) || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/resolve-args.yaml
    with:
      allowed_comment: "snapshot"
  e2e-matrix:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      statuses: write # ./.github/actions/commit-status/start
    needs: [resolve]
    if: needs.resolve.outputs.SHOULD_RUN == 'true'
    uses: ./.github/workflows/e2e-matrix.yaml
    with:
      git_ref: ${{ needs.resolve.outputs.GIT_REF }}
      region: ${{ inputs.region || 'us-east-2' }}
      workflow_trigger: "matrix"
      # Default to true unless using a workflow_dispatch
      cleanup: ${{ github.event_name != 'workflow_dispatch' && true || inputs.cleanup }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
