name: E2EMatrix
on:
  workflow_call:
    inputs:
      region:
        type: string
        default: "us-east-2"
      k8s_version:
        type: string
        default: "1.28"
      eksctl_version:
        type: string
        default: v0.160.0-rc.0
      git_ref:
        type: string
      workflow_trigger:
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      region:
        type: choice
        options:
          - "us-east-2"
          - "us-west-2"
        default: "us-east-2"
      k8s_version:
        type: choice
        options:
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
          - "1.27"
          - "1.28"
        default: "1.28"
      eksctl_version:
        type: string
        default: v0.160.0-rc.0
# All jobs will run under the following conditions:
#   1. Upstream Karpenter repo triggered the job by schedule, push, or dispatch
#   2. Upstream Karpenter repo triggered the job by workflow_run, which requires maintainer check to succeed
#   3. Downstream fork triggered the job through dispatch and has set 'ENABLE_E2E' in repo environment variables
jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        suite: [Integration, Machine, Consolidation, Utilization, Interruption, Drift, Expiration, Chaos, IPv6]
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      git_ref: ${{ inputs.git_ref }}
      region: ${{ inputs.region }}
      k8s_version: ${{ inputs.k8s_version }}
      eksctl_version: ${{ inputs.eksctl_version }}
      workflow_trigger: ${{ inputs.workflow_trigger }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  e2e-upgrade:
    uses: ./.github/workflows/e2e-upgrade.yaml
    with:
      # This version matches the steps of the newest version of the install-eksctl action
      # which will take in the eksctl_version into the composite action
      from_git_ref: 3519331035579ac0caf66a7f5a5282a2fef9b409
      to_git_ref: ${{ inputs.git_ref }}
      region: ${{ inputs.region }}
      k8s_version: ${{ inputs.k8s_version }}
      eksctl_version: ${{ inputs.eksctl_version }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
