name: E2ECleanup
on:
  workflow_dispatch:
    inputs:
      cluster_name:
        type: string
        required: true
      git_ref:
        type: string
      region:
        type: choice
        options:
          - "us-east-1"
          - "us-east-2"
          - "us-west-2"
          - "eu-west-1"
jobs:
  cleanup:
    name: cleanup-${{ inputs.cluster_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git_ref }}
      - name: cleanup karpenter and cluster '${{ inputs.cluster_name }}' resources
        uses: ./.github/actions/e2e/cleanup
        with:
          account_id: ${{ vars.ACCOUNT_ID }}
          role: ${{ vars.ROLE_NAME }}
          region: ${{ inputs.region }}
          cluster_name: ${{ inputs.cluster_name }}
          git_ref: ${{ inputs.git_ref }}
          eksctl_version: v0.163.0