name: E2EMatrix
on:
  workflow_call:
    inputs:
      region:
        type: string
        default: "us-east-2"
      k8s_version:
        type: string
        default: "1.28"
      cleanup:
        type: boolean
        required: true
      git_ref:
        type: string
      workflow_trigger:
        type: string
        required: true
      parallelism:
        type: number
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
  workflow_dispatch:
    inputs:
      region:
        type: choice
        options:
          - "us-east-1"
          - "us-east-2"
          - "us-west-2"
          - "eu-west-1"
        default: "us-east-2"
      k8s_version:
        type: choice
        options:
          - "1.23"
          - "1.24"
          - "1.25"
          - "1.26"
          - "1.27"
          - "1.28"
        default: "1.28"
      cleanup:
        type: boolean
        required: true
        default: true
# All jobs will run under the following conditions:
#   1. Upstream Karpenter repo triggered the job by schedule, push, or dispatch
#   2. Upstream Karpenter repo triggered the job by workflow_run, which requires maintainer check to succeed
#   3. Downstream fork triggered the job through dispatch and has set 'ENABLE_E2E' in repo environment variables
jobs:
  e2e:
    strategy:
      fail-fast: false
      max-parallel: ${{ inputs.parallelism || 100 }}
      matrix:
        suite:
          - Integration
          - NodeClaim
          - Consolidation
          - Interruption
          - Drift
          - Expiration
          - Chaos
          - IPv6
          - PrivateCluster
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: ${{ matrix.suite }}
      git_ref: ${{ inputs.git_ref }}
      region: ${{ inputs.region }}
      k8s_version: ${{ inputs.k8s_version }}
      cleanup: ${{ inputs.cleanup }}
      workflow_trigger: ${{ inputs.workflow_trigger }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  e2e-upgrade:
    uses: ./.github/workflows/e2e-upgrade.yaml
    with:
      # This version matches the steps of the newest version that contains the additional step
      # of deploying the instance profile so that the pre-upgrade and post-upgrade create-cluster
      # actions have the same number of steps and don't fail during post-cleanup
      from_git_ref: 62c25a3ea85c7d00165e60a913fff1ec7c1f29fd
      to_git_ref: ${{ inputs.git_ref }}
      region: ${{ inputs.region }}
      k8s_version: ${{ inputs.k8s_version }}
      cleanup: ${{ inputs.cleanup }}
      workflow_trigger: ${{ inputs.workflow_trigger }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
