name: E2EVersionCompatibilityTrigger
on:
  schedule:
    # The test will run every Monday, Thursday at 12:07 AM UTC
    - cron: '7 0 * * 1,4'
  workflow_run:
    workflows: [ApprovalComment]
    types: [completed]
  workflow_dispatch:
    inputs:
      region:
        required: true
        default: 'eu-west-1'
        type: choice
        options:
          - "us-east-1"
          - "eu-west-1"
      cleanup:
        required: true
        default: true
        type: boolean
jobs:
  resolve:
    if: (github.repository == 'aws/karpenter-provider-aws' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')) || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/resolve-args.yaml
    with:
      allowed_comment: "versionCompatibility"
  versionCompatibility:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
      statuses: write # ./.github/actions/commit-status/start
    needs: [resolve]
    if: needs.resolve.outputs.SHOULD_RUN == 'true'
    strategy:
      fail-fast: false
      matrix:
        k8s_version: ["1.29", "1.30", "1.31", "1.32", "1.33", "1.34", "1.35"]
    uses: ./.github/workflows/e2e-matrix.yaml
    with:
      region: ${{ inputs.region || 'eu-west-1' }}
      git_ref: ${{ needs.resolve.outputs.GIT_REF }}
      k8s_version: ${{ matrix.k8s_version }}
      workflow_trigger: "versionCompatibility"
      # Default to true unless using a workflow_dispatch
      cleanup: ${{ github.event_name != 'workflow_dispatch' && true || inputs.cleanup }}
      parallelism: 1
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
