name: Nightly
on:
  schedule:
    - cron: '30 12 * * *'
  push:
  pull_request:
permissions:
  id-token: write
jobs:
  nightly:
    if: github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::274912145732:role/Snapshots
          aws-region: us-east-1
      - run: make nightly
        env:
          CLOUD_PROVIDER: aws
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
