name: ResourceCount
on:
  schedule:
    - cron: '3 */1 * * *' # every hour
  workflow_dispatch:
permissions:
  id-token: write # aws-actions/configure-aws-credentials@v4.0.1
jobs:
  counter:
    if: vars.CI_ACCOUNT_ID != '' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        region: [us-east-2, us-west-2, eu-west-1, eu-north-1, us-east-1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.CI_ACCOUNT_ID }}:role/${{ vars.CI_ROLE_NAME }}
          aws-region: ${{ matrix.region }}
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: test/hack/resource/go.mod
          check-latest: true
          cache-dependency-path: "test/hack/resource/go.sum"
      - run: go run main.go
        working-directory: ./test/hack/resource/count
        name: "Run resource count script"
