name: ResourceCount
on:
  schedule:
    - cron: '3 */1 * * *' # every hour
  workflow_dispatch:
permissions:
  id-token: write # aws-actions/configure-aws-credentials@v4.0.1
jobs:
  counter:
    if: vars.ACCOUNT_ID != '' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        region: [us-east-2, us-west-2, eu-west-1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/${{ vars.ROLE_NAME }}
          aws-region: ${{ matrix.region }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: test/hack/resource/go.mod
          check-latest: true
          cache-dependency-path: "test/hack/resource/go.sum"
      - run: go run main.go
        working-directory: ./test/hack/resource/count
        name: "Run resource count script"
