name: StableRelease
on:
  workflow_run:
    workflows: [ReleaseTag]
    types: [completed]
permissions:
  id-token: write
  pull-requests: write
  contents: write
jobs:
  stable-release:
    if: github.event.workflow_run.conclusion == 'success' && github.repository == 'aws/karpenter'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/download-artifact
      - run: |
          tag=$(head -n 1 /tmp/artifacts/metadata.txt)
          tag_commit=$(tail -n 1 /tmp/artifacts/metadata.txt)
          echo "TAG_COMMIT=$tag_commit" >> $GITHUB_ENV
          echo "TAG=$tag" >> $GITHUB_ENV
      - name: Checkout the repository out again at the given SHA from the artifact
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.TAG_COMMIT }}
      - uses: ./.github/actions/install-go-and-dependencies
      - uses: ./.github/actions/authenticate-aws
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Snapshot Release
        run: make release
      - name: Checkout the repository out again at the given SHA from the artifact
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.TAG_COMMIT }}
      - name: Publish images and Helm chart
        run: make release
        env:
          RELEASE_VERSION: ${{ env.TAG }}
      - name: Autogenerate and commit files for PR
        run: |
          make docgen
          make prepare-website
          make stable-release-pr
        env:
          RELEASE_VERSION: ${{ env.TAG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
      - name: Create PR
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'chore: Release ${{ env.STABLE_RELEASE_VERSION }}',
              owner,
              repo,
              head: 'release-${{ env.STABLE_RELEASE_VERSION }}',
              base: 'main',
              body: [
                'Stable Release Changes for ${{ env.STABLE_RELEASE_VERSION }}.',
                'Please disregard this PR if it is for a patch release.',
                'Please remove the branch after merging.',
                'This PR is generated by [StableRelease](https://github.com/aws/karpenter/actions/workflows/stable-release.yml).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['stable-release','website','helm-charts']
            });
