name: Sweeper
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  sweeper:
    permissions:
      id-token: write # aws-actions/configure-aws-credentials@v4.0.1
    if: vars.CI_ACCOUNT_ID != '' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        region: [us-east-2, us-west-2, eu-west-1, eu-north-1, us-east-1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8 # v5.1.0
        with:
          role-to-assume: arn:aws:iam::${{ vars.CI_ACCOUNT_ID }}:role/${{ vars.CI_ROLE_NAME }}
          aws-region: ${{ matrix.region }}
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: test/hack/resource/go.mod
          check-latest: true
          cache-dependency-path: "test/hack/resource/go.sum"
      # eu-north-1 contains the soak tests and resources should be swept if they are older than 8 days
      - run: |
          if [[ "${{ matrix.region }}" == "eu-north-1" ]]; then
            go run main.go --expiration 192h
          else
            go run main.go --expiration 12h
          fi
        working-directory: ./test/hack/resource/clean
        name: "Run cleanup script"
