name: WebsitePreviewTrigger
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  preview-trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/karpenter-provider-aws'
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
      - name: Save info about the review comment as an artifact for other workflows that run on workflow_run to download them
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: |
          mkdir -p /tmp/artifacts
          { echo "$PULL_REQUEST_NUMBER"; echo "$COMMIT_ID"; } >> /tmp/artifacts/website-metadata.txt
          cat /tmp/artifacts/website-metadata.txt
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: artifacts
          path: /tmp/artifacts
