name: WebsitePreviewTrigger
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  preview-trigger:
    runs-on: ubuntu-latest
    if: github.repository == 'aws/karpenter-provider-aws'
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0
      - name: Save info about the PR as an artifact for other workflows that run on workflow_run to download them
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_ID: ${{ github.event.pull_request.head.sha }}
        run: |
          mkdir -p /tmp/artifacts
          { echo "$PULL_REQUEST_NUMBER"; echo "$COMMIT_ID"; } >> /tmp/artifacts/website-metadata.txt
          cat /tmp/artifacts/website-metadata.txt
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: artifacts
          path: /tmp/artifacts
